media: public/img
content:
  - name: projects
    label: Проекты
    type: collection
    path: content/projects
    filename: "{{ fields.title }}"
    subfolders: false
    view:
      fields: [title, draft, status]
    fields:
      - name: title
        label: Заголовок
        type: string
        required: true
        description: "Например: Водопроводная, 14"
      - name: title
        label: Транслитерация для ссылки
        type: string
        required: true
        description: "Например: vodoprovodnaya-14"
      - name: string
        label: Ссылка
        type: string
        description: "Например: https://ddkolesnik.com/projects/vodoprovodnaya-14"
      - name: is_big
        label: Большая иконка
        type: boolean
      - name: cover
        label: Обложка
        type: image
      - name: draft
        label: Черновик
        type: boolean
      - name: latitude
        label: Широта
        type: number
        step: 0.000001
        options:
          min: -180
          max: 180
      - name: longitude
        label: Долгота
        type: number
        step: 0.000001
        options:
          min: -180
          max: 180
      - name: status
        label: Статус
        type: select
        options:
          values:
            - value: done
              label: Завершён
            - value: in_progress
              label: В работе
            - value: invest
              label: Для инвестиций
      - name: body
        label: Описание
        type: rich-text
        options:
          media: false
